export default [
  {
    fileName: "API Access Rate Architect Full-Stack IaC - fix.drawio.png",
    objectFit: "object-contain",
  },
  {
    fileName: "application-composer-template.yaml.png",
    objectFit: "object-cover",
  },
  { fileName: "complete-tls.drawio.png", objectFit: "object-contain" },
  { fileName: "federation.drawio.png", objectFit: "object-contain" },
  { fileName: "cognito.drawio.png", objectFit: "object-contain" },
  { fileName: "cloudformation-2.drawio.png", objectFit: "object-contain" },
  {
    fileName: "app-login-refresh-flow.drawio.png",
    objectFit: "object-contain",
  },
  { fileName: "intro-diagram.drawio.png", objectFit: "object-contain" },
  { fileName: "api-bypass-2.drawio.png", objectFit: "object-contain" },
  { fileName: "api-bypass-3.drawio.png", objectFit: "object-contain" },
  { fileName: "iam-2.drawio.png", objectFit: "object-contain" },
  { fileName: "iam-role.drawio.png", objectFit: "object-contain" },
  { fileName: "remove-api-gateway.drawio.png", objectFit: "object-contain" },
  { fileName: "cloudtrail-1.drawio.png", objectFit: "object-contain" },
  { fileName: "eventbridge.drawio.png", objectFit: "object-contain" },
  { fileName: "sam-kinesis.drawio.png", objectFit: "object-contain" },
  { fileName: "api-gateway-1.drawio.png", objectFit: "object-contain" },
  { fileName: "api-gateway-2.drawio.png", objectFit: "object-contain" },
  { fileName: "5.drawio.png", objectFit: "object-contain" },
  { fileName: "vpc-4.drawio.png", objectFit: "object-contain" },
  { fileName: "privatelink-5.drawio.png", objectFit: "object-contain" },
  { fileName: "kinesis.drawio.png", objectFit: "object-contain" },
  { fileName: "idempotency-check.drawio.png", objectFit: "object-contain" },
  { fileName: "sqs-sns.drawio.png", objectFit: "object-contain" },
  { fileName: "vpc-3.drawio.png", objectFit: "object-contain" },
  { fileName: "api-gateway-3.drawio.png", objectFit: "object-contain" },
  { fileName: "deploy-1.drawio.png", objectFit: "object-contain" },
  { fileName: "privatelink-4.drawio.png", objectFit: "object-contain" },
  { fileName: "api-gateway-4.drawio.png", objectFit: "object-contain" },
  { fileName: "sqs-breakdown.drawio.png", objectFit: "object-contain" },
  { fileName: "vpc.png", objectFit: "object-contain" },
  { fileName: "api-gateway-5.drawio.png", objectFit: "object-contain" },
  { fileName: "small architecture.drawio.png", objectFit: "object-contain" },
  { fileName: "api-proxy.drawio.png", objectFit: "object-contain" },
  { fileName: "3.drawio.png", objectFit: "object-contain" },
  { fileName: "7.drawio.png", objectFit: "object-contain" },
  { fileName: "aws-async-pattern.drawio.png", objectFit: "object-contain" },
  { fileName: "aws-social.drawio.png", objectFit: "object-contain" },
  { fileName: "cloudformation-0.drawio.png", objectFit: "object-contain" },
  { fileName: "cloudformation-1.drawio.png", objectFit: "object-contain" },
  { fileName: "cloudformation-3.drawio.png", objectFit: "object-contain" },
  { fileName: "cloudtrail-2.drawio.png", objectFit: "object-contain" },
  { fileName: "cloudtrail-3.drawio.png", objectFit: "object-contain" },
  { fileName: "cloudwatch-2.drawio.png", objectFit: "object-contain" },
  { fileName: "cloudwatch.drawio.png", objectFit: "object-contain" },
  { fileName: "what-https-does.drawio.png", objectFit: "object-contain" },
  { fileName: "cognito-authorizer-2.drawio.png", objectFit: "object-contain" },
  { fileName: "cognito-authorizer.drawio.png", objectFit: "object-contain" },
  { fileName: "cognito-intro.drawio.png", objectFit: "object-contain" },
  { fileName: "create-api-key.drawio.png", objectFit: "object-contain" },
  { fileName: "create-user.drawio.png", objectFit: "object-contain" },
  { fileName: "data-transfer-out-1.drawio.png", objectFit: "object-contain" },
  { fileName: "data-transfer-out-2.drawio.png", objectFit: "object-contain" },
  { fileName: "dlq-alarm-topic.drawio.png", objectFit: "object-contain" },
  { fileName: "dynamo-1.drawio.png", objectFit: "object-contain" },
  { fileName: "dynamo-2.drawio.png", objectFit: "object-contain" },
  { fileName: "dynamo-3.drawio.png", objectFit: "object-contain" },
  { fileName: "dynamo-4.drawio.png", objectFit: "object-contain" },
  { fileName: "dynamodb-stream.drawio.png", objectFit: "object-contain" },
  { fileName: "ec2-1.drawio.png", objectFit: "object-contain" },
  { fileName: "ec2-2.drawio.png", objectFit: "object-contain" },
  { fileName: "ec2-3.drawio.png", objectFit: "object-contain" },
  { fileName: "Enhanced Fan-Out.drawio.png", objectFit: "object-contain" },
  {
    fileName: "event-driven-architecture.drawio.png",
    objectFit: "object-contain",
  },
  { fileName: "eventbus.png", objectFit: "object-contain" },
  { fileName: "full-api-key-edit.drawio.png", objectFit: "object-contain" },
  { fileName: "how-mtls-works.drawio.png", objectFit: "object-contain" },
  { fileName: "iam-1.drawio.png", objectFit: "object-contain" },
  { fileName: "iam-3.drawio.png", objectFit: "object-contain" },
  { fileName: "iam-4.drawio.png", objectFit: "object-contain" },
  { fileName: "iam-5.drawio.png", objectFit: "object-contain" },
  { fileName: "iam-policy.drawio.png", objectFit: "object-contain" },
  { fileName: "clientside-tls.drawio.png", objectFit: "object-contain" },
  { fileName: "key-interception.drawio.png", objectFit: "object-contain" },
  { fileName: "kinesis limits.drawio.png", objectFit: "object-contain" },
  { fileName: "lambda to kinesis.drawio.png", objectFit: "object-contain" },
  { fileName: "lambda-1.drawio.png", objectFit: "object-contain" },
  { fileName: "lambda-2.drawio.png", objectFit: "object-contain" },
  { fileName: "lambda-concurrency.drawio.png", objectFit: "object-contain" },
  { fileName: "lambda-layers.drawio.png", objectFit: "object-contain" },
  { fileName: "middleware.png", objectFit: "object-contain" },
  { fileName: "Untitled Diagram.drawio (3).png", objectFit: "object-cover" },
  { fileName: "user services.png", objectFit: "object-cover" },
  { fileName: "fullstack.png", objectFit: "object-cover" },
  { fileName: "oac.drawio.png", objectFit: "object-contain" },
  { fileName: "oauthlogin.png", objectFit: "object-contain" },
  { fileName: "obtain-crt-tls.drawio.png", objectFit: "object-contain" },
  {
    fileName: "payment-failure-and-success.drawio.png",
    objectFit: "object-contain",
  },
  { fileName: "payment-success.drawio.png", objectFit: "object-contain" },
  { fileName: "permissions-triangle.drawio.png", objectFit: "object-contain" },
  { fileName: "privatelink-2.drawio.png", objectFit: "object-contain" },
  { fileName: "privatelink-3.drawio.png", objectFit: "object-contain" },
  {
    fileName: "public-vpc-communication.drawio.png",
    objectFit: "object-contain",
  },
  { fileName: "PullRequest.drawio.png", objectFit: "object-contain" },
  { fileName: "react.drawio.png", objectFit: "object-contain" },
  { fileName: "recurring-billing.drawio.png", objectFit: "object-contain" },
  { fileName: "resource-based-policy.drawio.png", objectFit: "object-contain" },
  {
    fileName: "alb-request-traversal-path.drawio.png",
    objectFit: "object-contain",
  },
  {
    fileName: "route53-and-certificate-manager.drawio.png",
    objectFit: "object-contain",
  },
  { fileName: "s3-1.drawio.png", objectFit: "object-contain" },
  { fileName: "s3-2.drawio.png", objectFit: "object-contain" },
  { fileName: "sam-1.drawio.png", objectFit: "object-contain" },
  { fileName: "sam-2.drawio.png", objectFit: "object-contain" },
  { fileName: "sam-3.drawio.png", objectFit: "object-contain" },
  { fileName: "sam-4.drawio.png", objectFit: "object-contain" },
  { fileName: "sam-5.drawio.png", objectFit: "object-contain" },
  { fileName: "sam-6.drawio.png", objectFit: "object-contain" },
  { fileName: "sam.drawio.png", objectFit: "object-contain" },
  { fileName: "SamPipeline.drawio.png", objectFit: "object-contain" },
  { fileName: "scope-1.drawio.png", objectFit: "object-contain" },
  { fileName: "scope-2.drawio.png", objectFit: "object-contain" },
  { fileName: "session-refresh.drawio.png", objectFit: "object-contain" },
  {
    fileName: "sns-sqs-invoked-lambda-1.drawio.png",
    objectFit: "object-contain",
  },
  {
    fileName: "sns-sqs-invoked-lambda-2.drawio.png",
    objectFit: "object-contain",
  },
  { fileName: "sns.drawio.png", objectFit: "object-contain" },
  { fileName: "api-bypass-1.drawio.png", objectFit: "object-contain" },
  { fileName: "sqs.drawio.png", objectFit: "object-contain" },
  { fileName: "standard-login.png", objectFit: "object-contain" },
  { fileName: "synchronous-payments.drawio.png", objectFit: "object-contain" },
  { fileName: "throttled-api.drawio.png", objectFit: "object-contain" },
  { fileName: "tls-on-aws.drawio.png", objectFit: "object-contain" },
  { fileName: "triple-key-set.drawio.png", objectFit: "object-contain" },
  { fileName: "true-login.drawio.png", objectFit: "object-contain" },
  { fileName: "vpc-1.drawio.png", objectFit: "object-contain" },
  { fileName: "vpc-2.drawio.png", objectFit: "object-contain" },
  { fileName: "vpc-architecture.drawio.png", objectFit: "object-contain" },
  { fileName: "vpclink.drawio.png", objectFit: "object-contain" },
  { fileName: "Webhook.drawio.png", objectFit: "object-contain" },
];
